// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZtxR-0jAsyGz06MXUMjvq1tnr1I3PNE',
    appId: '1:1029075571218:web:ee410ed4674996a5dbfecb',
    messagingSenderId: '1029075571218',
    projectId: 'agri-wise-1cd4c',
    authDomain: 'agri-wise-1cd4c.firebaseapp.com',
    storageBucket: 'agri-wise-1cd4c.firebasestorage.app',
    measurementId: 'G-W8RS5VW5PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO35PhUOkzNridI5RwnAhRErbXczpkNhM',
    appId: '1:1029075571218:android:e205cfbcd7df07bbdbfecb',
    messagingSenderId: '1029075571218',
    projectId: 'agri-wise-1cd4c',
    storageBucket: 'agri-wise-1cd4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBY6mhSDdsqBtUU52_yNJcEfmhMxbO8Ps',
    appId: '1:1029075571218:ios:c26b380fcc8a7702dbfecb',
    messagingSenderId: '1029075571218',
    projectId: 'agri-wise-1cd4c',
    storageBucket: 'agri-wise-1cd4c.firebasestorage.app',
    iosBundleId: 'com.example.agriWise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEZtxR-0jAsyGz06MXUMjvq1tnr1I3PNE',
    appId: '1:1029075571218:web:d858501bbc60f141dbfecb',
    messagingSenderId: '1029075571218',
    projectId: 'agri-wise-1cd4c',
    authDomain: 'agri-wise-1cd4c.firebaseapp.com',
    storageBucket: 'agri-wise-1cd4c.firebasestorage.app',
    measurementId: 'G-Z4RNC3632E',
  );
}
